### ISSUE TITLE
CircularRevealAnim文件中的startRadius = Of中的Of是什么?

### ISSUE THREAD

**Issue by EdwinSmartBoy** [LRH1993/Eyepetizer-in-Kotlin#14]

**Comment by LRH1993** [comment]
0f->0

**Comment by EdwinSmartBoy** [comment]
您好,我想问的是,Of这个是在什么地方定义过的吗? 因为我在当前文件下没有找到该变量名,您在CircularRevealAnim文件中的代码如下:
if (isShow) {
            startRadius = Of
            endRadius = maxRadius
        } else {
            startRadius = maxRadius
            endRadius = Of
        }

还望您能给我详解一下,谢谢您

**Comment by EdwinSmartBoy** [comment]
[捂脸][捂脸][捂脸][捂脸][捂脸][捂脸][捂脸][捂脸][捂脸] 那个其实不是of  是0f是吧?
